\version: "3"

services:
  nginx:
    image: nginx:1.17.4-alpine
    container_name: nginx_config
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default/conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres_config
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      TZ: "Asia/Jakarta"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "docker"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped
    tty: true
    container_name: php_config
    volumes:
      - ./src:/var/www/html

    networks:
      - laravel

networks:
  laravel:
